### ISSUE TITLE
managerMain에서 NullPointerException

### ISSUE THREAD

**Issue by Isaac-Lee** [JayJay-H/British_in_December#72]
at Connect_to_MariaDB/Manager.Java.Controllers.ScooterManagementController.findScooterList(ScooterManagementController.java:204)
	at Connect_to_MariaDB/Manager.Java.Controllers.ScooterManagementController.setField(ScooterManagementController.java:78)
	at Connect_to_MariaDB/Manager.Java.Controllers.ManagerController.ScooterManagementButtonHandler(ManagerController.java:74)

**Comment by Isaac-Lee** [comment]
로컬 DB에 아무 것도 없어서 그런것 같음

**Comment by uinone** [comment]
확인

**Comment by uinone** [comment]
해결
